### ISSUE TITLE
Rstudio v2022.02.2+485 and R 4.2 Dockerfile update

### ISSUE THREAD

**Issue by sebacea** [ppc64le/build-scripts#2119]
Hi I am using r/rstudio/Dockerfiles/v1.3.1073/Dockerfile but needing an update of RStudio and R. For R it is necessary to update to ubuntu focal. I tried to update the Dockerfile that I personally updated in the past without success. See #706 

Thanks @seth-priya @gerrith3

**Comment by seth-priya** [comment]
@sebacea just to let you know I have been looking at this a bit in the background and I have been able to update the base image to focal, install the right dependencies and build R 4.2. The RStudio build seems to have a few issues atleast : a) it integrates with crashpad for crash reporting feature and that/the version that is integrated does not have ppc64le support, it fails in the "mini_chromium" module and since this comes from the chromium tree https://github.com/chromium/mini_chromium, which again does not have ppc64le support, I don't expect that this will be an easy one to solve and hence I have disable the crash reporting feature for now; b) it is pulling the x86 specific nodejs binaries - this should be an easy fix once  we can trace down the exact origin.

With the above, I have been able to build the rstudio-core, rstudio-r, rstudio-server-core, rsession, rserver and other sub-components of these. It is failing while building gwt_build, which is a java based component

I will share more updates as I have them

**Comment by sebacea** [comment]
Nice! Many many thanks!

Le mar. 14 juin 2022 à 01:30, Priya Seth ***@***.***> a
écrit :

**Comment by seth-priya** [comment]
@sebacea can you please confirm if disabling crashpad will work for you or do you specifically need the crash reporting feature (that is likely to add significantly to the complexity)? We should hopefully be able to get you a working version without crashpad in the next couple of weeks, is that good enough for you from a timeline perspective as well?

**Comment by sebacea** [comment]
@seth-priya did you commit the Dockerfile you used for updating to focal and R 4.2?

**Comment by seth-priya** [comment]
@sebacea not yet because as I mentioned there are still unresolved issues in building the java components, I can try to get a draft PR with whatever I have by Tuesday/Wednesday if I am not able to solve other issues by then

**Comment by seth-priya** [comment]
@sebacea this should be address with https://github.com/ppc64le/build-scripts/pull/2277 , please let us know in case of issues, thanks
