### ISSUE TITLE
Fluentbit not working after v1.8.12

### ISSUE THREAD

**Issue by zeusng-fast** [ppc64le/build-scripts#2225]
The fluent-bit patch works very well up to v1.8.12. After that, it is failing again.

**Comment by seth-priya** [comment]
@zeusng-fast can you please give us some insights into the need for this so that we can prioritize it accordingly? We had got a recent request from a customer and had tried to rebase the patch for top-of-tree but had observed that fluent-bit, though built, was crashing at runtime. We had later abandoned the effort as the customer decided to go with fluentd instead. Would fluentd be an alternative for what you are doing? as that is pretty well supported on Power today. cc @gerrith3

**Comment by zeusng-fast** [comment]
@seth-priya like you said, the build pass v1.8.12 is successful but fluent-bit crash at runtime. We have been using fluent-bit as a sidecar to our container for a while on Power due to it's lightweight implementation as compared to fluentd. It is deployed as a POD from Operator. Changing to fluentd is not preferred as we have to provide migration path for our existing customers.

**Comment by gerrith3** [comment]
Hi @zeusng-fast - thanks for the request and we are looking at it.  You mention that you have customers - do you have a formal relationship with IBM or the IBM Power Brand?  If so it would be good to bring this in through that channel as well to help with prioritizing this.  We have worked on it previously and as Priya says, this one has had troubles with porting to Power, in part because of the dependency on luajit.  As this one is a more difficult port and we have a relatively small team, we'd need more information for it to "jump the porting queue" as it were.  Also, how long can you survive on the previous version, or what is a hard need-by date?  I can't promise that we can hit that because of the complexity but we will look and see what we can do.

**Comment by zeusng-fast** [comment]
Hi @gerrith3 , I have forwarded this thread to our IBM counterpart responsible for Power. To give you perspective, release v1.8 is now on maintenance mode and we can't even upgrade to v1.8.5. We need to look at v1.9.x release very soon.

**Comment by gerrith3** [comment]
;.qrd=+

**Comment by sumitd2** [comment]
@zeusng-fast, we are working on the issue. We've fixed the crash but are observing these test failures (v1.9.5):
51 - flb-rt-out_s3 (Failed)
52 - flb-rt-out_td (Failed)
56 - flb-it-pack (Failed)
62 - flb-it-network (Failed)
66 - flb-it-utils (Failed)
99 - flb-it-lua (Failed)
These tests are not being executed by the script you currently have. Will keep you updated.

**Comment by seth-priya** [comment]
@zeusng-fast  we have the updated build script available at https://github.com/ppc64le/build-scripts/tree/master/f/fluent-bit/v1.9.5 , please let us know in case of issues, thanks
